//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class montr_monitor_counters
    {
        public string machine_id { get; set; }
        public string counter_id { get; set; }
        public string instance_id { get; set; }
        public string instance_name { get; set; }
        public Nullable<int> display_order { get; set; }
        public Nullable<double> current_value { get; set; }
        public Nullable<System.DateTime> current_datetime { get; set; }
        public Nullable<double> minimum_value { get; set; }
        public Nullable<System.DateTime> minimum_datetime { get; set; }
        public Nullable<double> maximum_value { get; set; }
        public Nullable<System.DateTime> maximum_datetime { get; set; }
        public Nullable<double> average_value { get; set; }
        public Nullable<System.DateTime> average_datetime { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> insert_user_id { get; set; }
        public Nullable<System.DateTime> insert_dt { get; set; }
    }
}
