//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class montr_machines_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public montr_machines_list()
        {
            this.server_users = new HashSet<server_users>();
        }
    
        public string machine_id { get; set; }
        public string machine_name { get; set; }
        public string machine_description { get; set; }
        public string host_name { get; set; }
        public string ip_address { get; set; }
        public string os_name { get; set; }
        public Nullable<bool> is_current_machine { get; set; }
        public string conn_domain_name { get; set; }
        public string conn_user_name { get; set; }
        public string conn_user_password { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> insert_user_id { get; set; }
        public Nullable<System.DateTime> insert_dt { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<System.DateTime> update_dt { get; set; }
        public Nullable<int> delete_user_id { get; set; }
        public Nullable<System.DateTime> delete_dt { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> interval_timer { get; set; }
    
        public virtual server_groups server_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<server_users> server_users { get; set; }
    }
}
