//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class montr_monitor_groups_counters
    {
        public string machine_id { get; set; }
        public int group_id { get; set; }
        public string counter_id { get; set; }
        public string instance_id { get; set; }
    }
}
