//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class montr_monitor_rules
    {
        public int rule_id { get; set; }
        public string machine_id { get; set; }
        public string counter_id { get; set; }
        public string instance_id { get; set; }
        public string rule_field { get; set; }
        public string rule_math_symbol { get; set; }
        public double rule_value { get; set; }
        public byte rule_ocuurance_type { get; set; }
        public int ocuurance_interval { get; set; }
        public string display_level { get; set; }
        public int action_id { get; set; }
        public Nullable<System.DateTime> first_occurance_datetime { get; set; }
        public Nullable<System.DateTime> last_occurance_datetime { get; set; }
        public Nullable<int> occurance_count { get; set; }
        public Nullable<int> occurance_interval { get; set; }
        public Nullable<bool> is_alarm_raised { get; set; }
        public Nullable<bool> is_action_raised { get; set; }
    }
}
