//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class montr_transaction_calculated
    {
        public int transaction_id { get; set; }
        public string machine_id { get; set; }
        public string counter_id { get; set; }
        public string instance_id { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public Nullable<decimal> transaction_average { get; set; }
        public Nullable<decimal> transaction_minimum { get; set; }
        public Nullable<decimal> transaction_maximum { get; set; }
    }
}
