//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule_events
    {
        public int id { get; set; }
        public string counter_id { get; set; }
        public string instance_id { get; set; }
        public string rule_field { get; set; }
        public string rule_math_symbol { get; set; }
        public double rule_value { get; set; }
        public byte rule_ocuurance_type { get; set; }
        public int ocuurance_interval { get; set; }
        public string machine_id { get; set; }
        public int rule_id { get; set; }
        public int raised_action_id { get; set; }
        public System.DateTime raised_action_fire_date { get; set; }
        public Nullable<bool> is_ack { get; set; }
        public Nullable<System.DateTime> ack_date_time { get; set; }
        public Nullable<int> ack_user { get; set; }
    }
}
