//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class schd_schedulers_data
    {
        public int scheduler_id { get; set; }
        public string entity_type { get; set; }
        public string entity_id { get; set; }
        public bool schd_is_enabled { get; set; }
        public System.DateTime schd_duration_start_date { get; set; }
        public System.DateTime schd_duration_end_date { get; set; }
        public string schd_frequencey { get; set; }
        public string schd_daily_frequency { get; set; }
        public Nullable<System.TimeSpan> schd_daily_once_time { get; set; }
        public Nullable<byte> schd_daily_repeat_interval { get; set; }
        public string schd_daily_repeat_unit { get; set; }
        public Nullable<System.TimeSpan> schd_daily_repeat_start_time { get; set; }
        public Nullable<System.TimeSpan> schd_daily_repeat_end_time { get; set; }
        public Nullable<bool> schd_weekly_saturday { get; set; }
        public Nullable<bool> schd_weekly_sunday { get; set; }
        public Nullable<bool> schd_weekly_monday { get; set; }
        public Nullable<bool> schd_weekly_tuesday { get; set; }
        public Nullable<bool> schd_weekly_wednesday { get; set; }
        public Nullable<bool> schd_weekly_thursday { get; set; }
        public Nullable<bool> schd_weekly_friday { get; set; }
        public Nullable<byte> schd_monthly_day { get; set; }
    }
}
