//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class servers_updates
    {
        public int transaction_id { get; set; }
        public System.DateTime transaction_dt { get; set; }
        public string server_id { get; set; }
        public string sys_system_name { get; set; }
        public string sys_ip_address { get; set; }
        public string cpu_processor_id { get; set; }
        public string cpu_processor_name { get; set; }
        public Nullable<short> cpu_cores_count { get; set; }
        public Nullable<short> cpu_cores_enabled_count { get; set; }
        public Nullable<short> cpu_logical_processors_count { get; set; }
        public Nullable<short> cpu_max_clock_speed { get; set; }
        public Nullable<decimal> memory_total { get; set; }
        public Nullable<decimal> storage_total { get; set; }
    }
}
