//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_counters_categories
    {
        public string category_id { get; set; }
        public string category_description { get; set; }
        public string category_name { get; set; }
        public Nullable<byte> display_order { get; set; }
        public bool is_active { get; set; }
    }
}
