//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_calculated
    {
        public int id { get; set; }
        public Nullable<decimal> average { get; set; }
        public Nullable<decimal> minimum { get; set; }
        public Nullable<decimal> maximum { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string machine_id { get; set; }
        public string counter_id { get; set; }
        public string instance_id { get; set; }
    }
}
