//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.server_users = new HashSet<server_users>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> insert_user_id { get; set; }
        public Nullable<System.DateTime> insert_dt { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<System.DateTime> update_dt { get; set; }
        public Nullable<int> delete_user_id { get; set; }
        public Nullable<System.DateTime> delete_dt { get; set; }
        public string comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<server_users> server_users { get; set; }
    }
}
